import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {InstitutionClient} from '../src/data/institution-http.js';
import {campaignPages} from '../src/data/multi-refresh.js';
import {dom,text,interfaceHTML,parseNNLibraryPlan,type Row} from '../src/data/multi-parsers.js';
import {sources,type Institution} from '../src/data/source-registry.js';
import {publicFactsPolicies} from '../src/data/public-facts-policy.js';
import {bodyHash} from '../src/data/institutions.js';
import {cityDate,localISO,cities,type CityKey} from '../src/data/cities.js';
const [campaign='.cache/real-catalog/multi-city-20260928',output='docs/evidence/multi-city']=process.argv.slice(2),client=new InstitutionClient(resolve(campaign)),pages=campaignPages(client),parsed=JSON.parse(readFileSync(resolve(campaign,'multi-parsed-rows.json'),'utf8')) as {rows:Row[]},rows=parsed.rows;
const currentSources=[...new Set(rows.map(r=>r.event.provider))] as Institution[],samples:any[]=[],parsedStats=JSON.parse(readFileSync(resolve(campaign,'parse-outcomes.json'),'utf8'));
const normalize=(s:string)=>s.toLowerCase().replace(/ё/g,'е').replace(/[^\p{L}\p{N}]/gu,'');
for(const source of currentSources){const own=rows.filter(r=>r.event.provider===source),unique=[...new Map(own.map(r=>[r.event.id,r])).values()];
 if(source==='nn-library'&&unique.length<2){const page=pages.get('https://ngounb.ru/?p=26084');if(page){const archived=parseNNLibraryPlan(page,pages).find(r=>!unique.some(v=>v.event.id===r.event.id));if(archived)unique.push(archived);}}
 assert(unique.length>=2,'TWO_SOURCE_SAMPLES_REQUIRED:'+source);
 const difficult=unique.find(r=>r.event.price.kind==='RANGE'||r.event.tariffs?.length||r.event.occurrences.some(o=>o.availability||o.cancelled||o.closedDates?.length||o.kind==='FLEXIBLE_VISIT'))??unique.at(-1)!;
 const selected=[unique.find(r=>r.event.id!==difficult.event.id)!,difficult];
 for(const [index,row]of selected.entries()){const evidence=[...row.event.observations,...row.venue.observations].map(o=>{const page=[...pages.values()].find(p=>p.hash===o.provenance?.contentHash&&p.url===o.requestUrl);assert(page,'CACHE_EVIDENCE_MISSING:'+o.requestUrl);assert.equal(bodyHash(page.body),page.hash);return page;});
  const material=evidence.map(p=>text(dom(interfaceHTML(p))[0])+' '+p.body).join(' ');const normalized=normalize(material),titleFound=normalized.includes(normalize(row.event.title));assert(titleFound,'TITLE_NOT_IN_SOURCE:'+row.event.id);
  const dates=row.event.occurrences.map(o=>{assert.equal(o.timezone,cities[row.event.city as CityKey].timezone);if(o.start){assert(Number.isFinite(Date.parse(o.start)));assert.equal(cityDate(o.start,o.timezone),o.activeFrom);}if(o.durationMinutes&&o.end)assert.equal(Date.parse(o.end)-Date.parse(o.start!),o.durationMinutes*60000);return {kind:o.kind,start:o.start,end:o.end,from:o.activeFrom,through:o.activeThrough,timezone:o.timezone,availability:o.availability??'NOT_VERIFIED',cancelled:o.cancelled??null};});
  const active=rows.some(r=>r.event.id===row.event.id);
  samples.push({source,index:index+1,id:row.event.id,title:row.event.title,sourceUrl:row.event.sourceUrl,classification:active?'CURRENT_SOURCE_SAMPLE':'ENDED_PARSER_SAMPLE_NOT_COUNTED',dates,venue:{name:row.venue.title,address:row.venue.address},price:row.event.price,tariffs:row.event.tariffs??[],check:{cachedContentHashes:true,titleFound:true,scopeAndTimezone:true,difficultCase:index===1},evidence:[...new Map(evidence.map(p=>[p.hash,{url:p.url,hash:p.hash,fetchedAt:p.fetchedAt}])).values()]});
 }
}
const sourceOutcomes=Object.entries(sources).map(([id,s])=>{const requests=client.ledger.requests.filter(r=>new URL(r.url).hostname===new URL(s.origin).hostname),stats=parsedStats.perSource[id]??{sourceRecords:0,uniqueEvents:0},policy=publicFactsPolicies[id as keyof typeof publicFactsPolicies];return {id,city:s.city,institution:s.label.replace('Источник: ',''),domain:s.origin,ownershipEvidence:policy?.evidence.filter(u=>!/robots|\/afisha\/?$/.test(u))??[],entryPages:policy?.evidence??[],extractionChannel:policy?.channel??null,pagination:id==='chel-philharmonia'?'DEFAULT_PAGE_ONLY; robots blocks PAGEN; alternative NAV_PAGE duplicates':id==='operann'?'3 public HTML pages; separate API denied by robots':id==='spb-library'?'60 daily filters exhausted':id==='chel-library'?'5 linked pages exhausted':['permopera','meloman','filarm','spb-opera'].includes(id)?'Published month/page interface; see channel-outcomes':'Linked current listing scope; not entire institutional archive',outcome:stats.uniqueEvents?'PARSED_CURRENT_FACTS':id==='kamal'?'EXCLUDED_TERMS_11_2':requests.some(r=>/HTTP_403|HTTP_429|ACCESS_CHALLENGE/.test(r.outcome))?'ACCESS_BLOCKED':id==='mosconcert'||id==='nsk-museum'?'ROBOTS_DENIED':'NO_ACTIONABLE_EVENT_IN_ACQUIRED_SCOPE',requests:requests.length,bytes:requests.reduce((n,r)=>n+r.bytes,0),...stats,failures:[...new Set(requests.filter(r=>r.outcome!=='OK'&&r.outcome!=='REDIRECT'&&r.outcome!=='ROBOTS_ABSENT').map(r=>r.outcome))]};});
const ledger=client.ledger as any,receipt={version:1,result:'PASS',checks:samples.length,samples,acquisition:{httpRequests:ledger.requests.length,decodedBytes:ledger.bytes,decimalMB:ledger.bytes/1e6,chargedNetworkMs:ledger.networkMs,waves:ledger.waves,limits:ledger.limits,corrections:ledger.corrections,cacheDoesNotRenewFetchedAt:true,browserRequests:0,pdfTextExtraction:{documents:2,textCharacters:0,outcome:'IMAGE_ONLY_PDF; tariffs remain unknown'},stoppedBecause:'PRIMARY_TARGETS_AND_CITY_DEPTH_MET; selected productive public interfaces exhausted; 1000-event stretch not achieved'}};
mkdirSync(output,{recursive:true});writeFileSync(resolve(output,'source-samples.json'),JSON.stringify(receipt,null,2)+'\n');writeFileSync(resolve(output,'source-frontier.json'),JSON.stringify({version:1,scopeDays:60,sources:sourceOutcomes},null,2)+'\n');console.log(JSON.stringify({result:'PASS',sources:currentSources.length,samples:samples.length,requests:ledger.requests.length,bytes:ledger.bytes}));
